"""Shared command reference data for keyboard shortcuts."""

from typing import List, Tuple

COMMAND_REFERENCE: List[Tuple[str, str]] = [
    ("a", "Aim wand"),
    ("b", "Browse spell book"),
    ("c", "Close door"),
    ("d", "Drop item"),
    ("e", "Show equipment"),
    ("f", "Fire/throw"),
    ("g", "Pick up item"),
    ("i", "Open inventory"),
    ("j", "Jam door with spike"),
    ("l", "Look"),
    ("m", "Cast spell"),
    ("o", "Open door"),
    ("p", "Pray"),
    ("q", "Quaff potion"),
    ("r", "Read scroll"),
    ("s", "Search once"),
    ("t", "Take off equipment"),
    ("u", "Use staff"),
    ("v", "Version information"),
    ("w", "Wear/wield equipment"),
    ("x", "Exchange weapon hand"),
    (".", "Run"),
    ("-", "Move without pickup"),
    ("B", "Bash"),
    ("D", "Disarm trap"),
    ("E", "Eat food"),
    ("F", "Fill lamp"),
    ("G", "Gain spells"),
    ("L", "Locate map"),
    ("M", "Show reduced map"),
    ("R", "Rest"),
    ("S", "Toggle search mode"),
    ("T", "Tunnel/dig"),
    ("V", "View character"),
    ("{", "Inscribe item"),
    ("?", "Item reference"),
]

